package org.pascallexer;

public enum TokenType {
    AND, ARRAY, BEGIN, CASE, CONST, DIV, DO, DOWNTO, ELSE, END,
    FILE, FOR, FUNCTION, GOTO, IF, IN, LABEL, MOD, NIL, NOT, OF,
    OR, PACKED, PROCEDURE, PROGRAM, RECORD, REPEAT, SET, THEN,
    TO, TYPE, UNTIL, VAR, WHILE, WITH,

    INTEGER, REAL, BOOLEAN, STRING, CHAR, BYTE, SMALLINT, LONGINT,
    IDENT, INTEGER_LITERAL, REAL_LITERAL, CHAR_LITERAL, STRING_LITERAL,

    PLUS, MINUS, MUL, DIV_OP, ASSIGN, EQ, LT, GT, LE, GE, NE,

    LParen, RParen, LBracket, RBracket, LBrace, RBrace,
    SEMICOLON, COLON, COMMA, DOT, DOTDOT,

    EOF, ERROR
}
